### ISSUE TITLE
Grasp width in mm

### ISSUE THREAD

**Issue by caiobarrosv** [dougsm/ggcnn_kinova_grasping#10]
Hello there,

actually it is not an issue. 

Could you please give me a reference of the [equation](https://github.com/dougsm/ggcnn_kinova_grasping/blob/master/ggcnn_kinova_grasping/scripts/kinova_open_loop_grasp.py#L60-L63) you used  you used to transform pixels into mm? 

I am trying to get something to use in a UR5 arm with realsense d435 but I am a little bit lost. 

I really appreciate you help ;)

**Comment by dougsm** [comment]
G'day @caiobarrosv 
The issue here is my terrible documentation ;-)
The first calculation, to mm, is effectively an approximation of the field of view of the camera.  The network outputs the grasp width in image coordiantes (i.e. pixels), and this uses the field of view of the camera, some trig and the measured depth of the grasp to convert this to a width in real world coordiates.  I wasn't 100% sure just looking at it either, so I've sketched it in the attached image... hopefully that helps.

The second line of that equation is specific to the kinova gripper, which only lets you set position in terms of joint encoder positions.

If you're trying to use a different robot, I would recommend having a look at my other repo https://github.com/dougsm/mvp_grasp.  It is much more up to date, and much more nicely laid out.  There's a standalone ggcnn repo that just got some updates, and there are some examples of using the services with a franka emika panda robot.  Specifically this service which has the same functionality and is much nicer: https://github.com/dougsm/mvp_grasp/blob/master/ggcnn/ros_nodes/ggcnn_service.py

![IMG_20190718_084730](https://user-images.githubusercontent.com/26375098/74988888-c2e18100-548a-11ea-8232-a4ace9c2268d.jpg)

**Comment by caiobarrosv** [comment]
First of all thank you for the fast response. I really appreciate it.
It is well documented. The code is clear and easy to understand. You did a great job.

Now I complete understand what you did and I totally agree with it.
You really did something different in the mvp repo ([code](https://github.com/dougsm/mvp_grasp/blob/c301ba2f4b0c0fb0c92b61a34f2821e56c693163/ggcnn/ros_nodes/ggcnn_service.py#L98))

in this repo:
`g_width = 2 * ((CURR_Z + 0.07)) * np.tan(0.1 * grip_width / 2.0 / 180.0 * np.pi) * 1000`

in [mvp repo](https://github.com/dougsm/mvp_grasp):
`width_m = width_img / 300.0 * 2.0 * depth_crop * np.tan(self.cam_fov * self.img_crop_size/depth.shape[0] / 2.0 / 180.0 * np.pi)
`

Could you please clarify some other things? :)

1 - width_img / 300.0 is used only for resizing, right?

2 - In this case you generate an image and then select the position of the max pixel created from np.argmax(points_outs). By using depth_crop instead of CURR_Z + 0.07 you are considering the distance of the cam to the max_pixel instead of the height (as shown in this draw below), right? 
![SmartSelect_20200221-001549_OneNote](https://user-images.githubusercontent.com/28100951/75001224-89375880-543f-11ea-8275-94f875d012cd.jpg)

3 - When the height of the end effector varies, the grasp width also varies. Shouldn't it be constant regardless of the height? I am running a simulation in gazebo (I also have the real arm available) with the realsense d435 plugin in order to generate depth data.

![Screenshot from 2020-02-21 00-24-26](https://user-images.githubusercontent.com/28100951/75001577-9143c800-5440-11ea-94bb-6848409c0490.png)

4 - Why has grip_width been replaced with self.img_crop_size?

Thank you in advance :)

**Comment by dougsm** [comment]
Hmm... Interesting... I didn't realise they were different!

After some reverse engineering, I think I understand how I came to the second equation for width.  Both are approximations, but make some different assumptions.  Instead of treating one pixel as an angle in space, it maps the full field of view of the camera to a width in physical space, then computes a fraction of this based on the width output from ggcnn.  Fortunately they give practically identical results! (see graph below).

To answer your questions:
1. This should be relative to the size of the cropped depth image (which happens to be 300px), but should really be using the img_crop_size variable. I'll make a note to fix this.  
2. Yes that's right, both represent the same value -- the distance from the grasp to the camera.  The first way used the position of the gripper + the offset to the camera (presumably because this was more accurate than the depth camera values), the second uses the depth camera values directly.
3. The GG-CNN outputs the width in terms of pixels, so as the camera gets closer to an object, it should (in theory) output a larger value for the width because the object appears larger. And this will then be counteracted by the formula which scales by the depth.  I say in theory because the width output of the GG-CNN is probably the least accurate, probably due to the noisy training data, so there's no guarantee that it will adjust the width linearly as the depth changes (but it should be pretty close).
4. See below.

![IMG_20200221_151322](https://user-images.githubusercontent.com/26375098/75006263-e32a3380-54bc-11ea-8581-7a3211eabe1c.jpg)
![image](https://user-images.githubusercontent.com/26375098/75006271-e7eee780-54bc-11ea-9396-503d9f37b01b.png)

**Comment by caiobarrosv** [comment]
I understood the explanation for questions 1, 2 and 4.

In the case of question 3, the grasp width in mm must be at least constant as you said (when the depth is considered).

I recorded a video and plotted 2 graphics. The plot above shows the grasp width in mm and the plot below shows the height of the end effector relative to the base.
When the robot approaches the object, the grasp width must be the same (right?), but varies from 4.3 mm to 8 mm. You can see in the graph that when the robot moves downwards (red curve), the range also changes, but the depth should take care of that, right?

(I am using the same [equation](https://github.com/dougsm/mvp_grasp/blob/c301ba2f4b0c0fb0c92b61a34f2821e56c693163/ggcnn/ros_nodes/ggcnn_service.py#L98) you used in mvp repo)

![grasp_widthXheight](https://user-images.githubusercontent.com/28100951/75076556-45942b80-54df-11ea-9df6-653c0ceb29b4.gif)

--

EDIT:
It seems to work better now. I had to adjust some parameters to work better with the realsense d435 gazebo plugin. 

I really appreciate your help :)
